const isAutoMatchedVideoInfo = (videoInfo) => {
    return videoInfo?.isAutoGenerated === true || videoInfo?.submitterId === "system";
};

const getLyricsStartTimeSeconds = (firstLyricTime) => {
    if (firstLyricTime === null || firstLyricTime === undefined) {
        return null;
    }

    const parsedFirstLyricTime = Number(firstLyricTime);
    return Number.isFinite(parsedFirstLyricTime)
        ? parsedFirstLyricTime / 1000
        : null;
};

const getVideoSyncOffsetSeconds = (captionStartTime, lyricsStartTime, videoInfo) => {
    if (captionStartTime === null || captionStartTime === undefined) {
        return 0;
    }

    const parsedCaptionStartTime = Number(captionStartTime);
    if (!Number.isFinite(parsedCaptionStartTime)) {
        return 0;
    }

    if (lyricsStartTime === null || lyricsStartTime === undefined) {
        return 0;
    }

    const parsedLyricsStartTime = Number(lyricsStartTime);
    if (!Number.isFinite(parsedLyricsStartTime)) {
        return 0;
    }

    // System matches often use 0 as an unknown caption start. Treat that as song-start sync.
    if (isAutoMatchedVideoInfo(videoInfo) && Math.abs(parsedCaptionStartTime) < 0.001) {
        return 0;
    }

    return parsedCaptionStartTime - parsedLyricsStartTime;
};

const VIDEO_SYNC_INTERVAL_MS = 250;
const VIDEO_SYNC_SEEK_THRESHOLD_SECONDS = 0.5;
// Keep the outgoing artwork briefly while a new track's background is being
// resolved.  This avoids a black flash when YouTube or the helper takes a
// moment to produce its first frame.
const FALLBACK_CROSSFADE_MS = 420;

// Blurred artwork does not benefit from decoding the largest Spotify image.
// Prefer the medium/regular asset while blur is active, but keep xlarge for a
// sharp cover background so image quality is unchanged when blur is disabled.
const selectAlbumArtForBackground = (metadata = {}, blurAmount = 0) => {
    const blurred = Number(blurAmount) > 0;
    return blurred
        ? (metadata.image_large_url || metadata.image_url || metadata.image_xlarge_url || "")
        : (metadata.image_xlarge_url || metadata.image_large_url || metadata.image_url || "");
};

const resolveVideoSyncState = ({
    spotifyTime,
    lyricsStartTime,
    videoInfo,
    additionalDelaySeconds = 0,
    mapVideoTime,
}) => {
    const parsedSpotifyTime = Number(spotifyTime);
    const safeSpotifyTime = Number.isFinite(parsedSpotifyTime) ? parsedSpotifyTime : 0;
    const parsedAdditionalDelay = Number(additionalDelaySeconds);
    const safeAdditionalDelay = Number.isFinite(parsedAdditionalDelay) ? parsedAdditionalDelay : 0;
    const captionStartTime = videoInfo?.captionStartTime;
    const offset = getVideoSyncOffsetSeconds(captionStartTime, lyricsStartTime, videoInfo);
    const baseVideoTime = safeSpotifyTime + offset + safeAdditionalDelay;

    // The video has no timeline before 0. Keep its first frame still until the
    // Spotify position reaches the point that maps to the beginning of the video.
    if (baseVideoTime < 0) {
        return {
            baseVideoTime,
            targetVideoTime: 0,
            shouldHoldAtStart: true,
        };
    }

    const mappedVideoTime = typeof mapVideoTime === "function"
        ? Number(mapVideoTime(baseVideoTime, videoInfo?.skipSegments, captionStartTime))
        : baseVideoTime;

    return {
        baseVideoTime,
        targetVideoTime: Number.isFinite(mappedVideoTime) ? Math.max(0, mappedVideoTime) : 0,
        shouldHoldAtStart: false,
    };
};

const wrapVideoSyncTime = (targetVideoTime, duration) => {
    const parsedTarget = Number(targetVideoTime);
    const safeTarget = Number.isFinite(parsedTarget) ? Math.max(0, parsedTarget) : 0;
    const parsedDuration = Number(duration);
    if (Number.isFinite(parsedDuration) && parsedDuration > 0 && safeTarget >= parsedDuration) {
        return safeTarget % parsedDuration;
    }
    return safeTarget;
};

const syncYouTubePlayerTimeline = ({
    player,
    targetVideoTime,
    shouldHoldAtStart,
    shouldPlay,
    holdState,
}) => {
    if (!player || !holdState) return;

    const wasHoldingAtStart = holdState.isHolding === true;
    holdState.isHolding = shouldHoldAtStart === true;

    const playerState = player.getPlayerState();
    if (shouldHoldAtStart) {
        const currentVideoTime = player.getCurrentTime();
        const isAtStart = Number.isFinite(currentVideoTime) &&
            Math.abs(currentVideoTime) <= VIDEO_SYNC_SEEK_THRESHOLD_SECONDS;
        if (!wasHoldingAtStart || (!holdState.primePending && !isAtStart)) {
            // A paused YouTube iframe can keep painting its previous decoded frame
            // after seekTo(0). Let it reach PLAYING once so the frame is refreshed;
            // onStateChange pauses it again as soon as that frame is available.
            holdState.primePending = true;
            player.seekTo(0, true);
            player.playVideo();
            return;
        }

        if (holdState.primePending) {
            // Buffering can outlast a sync tick. Pausing here would cancel the
            // refresh and leave the previous frame visible for the whole intro.
            if (!settleYouTubeHoldPrime({ player, playerState, holdState }) &&
                playerState !== 1 && playerState !== 3) {
                if (!isAtStart) player.seekTo(0, true);
                player.playVideo();
            }
            return;
        }

        if (playerState === 1 || playerState === 3) {
            player.pauseVideo();
        }
        return;
    }

    holdState.primePending = false;
    const currentVideoTime = player.getCurrentTime();
    if (
        wasHoldingAtStart ||
        !Number.isFinite(currentVideoTime) ||
        Math.abs(currentVideoTime - targetVideoTime) > VIDEO_SYNC_SEEK_THRESHOLD_SECONDS
    ) {
        player.seekTo(targetVideoTime, true);
    }

    if (!shouldPlay) {
        if (playerState === 1 || playerState === 3) {
            player.pauseVideo();
        }
    } else if (playerState !== 1 && playerState !== 3) {
        player.playVideo();
    }
};

const settleYouTubeHoldPrime = ({ player, playerState, holdState }) => {
    if (
        !player ||
        playerState !== 1 ||
        holdState?.primePending !== true ||
        holdState?.isHolding !== true
    ) {
        return false;
    }

    // PLAYING may be queued from before seekTo(0). Wait until the player also
    // reports the start position, rather than freezing that stale frame again.
    const currentVideoTime = player.getCurrentTime();
    if (!Number.isFinite(currentVideoTime) ||
        Math.abs(currentVideoTime) > VIDEO_SYNC_SEEK_THRESHOLD_SECONDS) {
        return false;
    }

    holdState.primePending = false;
    player.pauseVideo();
    return true;
};

const disableYouTubeCaptions = (player) => {
    if (!player) return;

    try {
        if (typeof player.unloadModule === "function") {
            player.unloadModule("captions");
            player.unloadModule("cc");
        }
    } catch (e) { }

    try {
        if (typeof player.setOption === "function") {
            player.setOption("captions", "track", {});
            player.setOption("cc", "track", {});
        }
    } catch (e) { }
};

const isSpotifyPlaybackActive = (playerState = Spicetify.Player?.data) => {
    try {
        const isPaused = playerState?.is_paused ?? playerState?.isPaused;
        if (typeof isPaused === "boolean") {
            return !isPaused;
        }

        const isPlaying = playerState?.is_playing ?? playerState?.isPlaying;
        if (typeof isPlaying === "boolean") {
            return isPlaying;
        }

        return Boolean(Spicetify.Player?.isPlaying?.());
    } catch (e) {
        return false;
    }
};

const VideoBackground = ({ trackUri, firstLyricTime, brightness, blurAmount, coverMode, videoScale, externalVideoInfo, onLoadingChange }) => {
    const { useState, useEffect, useRef, useCallback } = react;
    const useIsoLayoutEffect = react.useLayoutEffect || useEffect;
    const VIDEO_BACKGROUND_DEBUG = false;
    const videoBackgroundDebug = (...args) => {
        if (VIDEO_BACKGROUND_DEBUG) {
            console.log(...args);
        }
    };
    const [videoInfo, setVideoInfo] = useState(null);
    const [isPlayerReady, setIsPlayerReady] = useState(false);
    const [videoLoadRevision, setVideoLoadRevision] = useState(0);

    const [stats, setStats] = useState({
        quality: '-',
        resolution: '-',
        buffered: '-',
        videoId: '-',
        videoHelper: '-',
        helperStatus: 'off'
    });

    const [helperStatus, setHelperStatus] = useState('off');

    const [showStats, setShowStats] = useState(false);
    const updateStats = useCallback((nextStats) => {
        setStats((prev) => {
            const next = typeof nextStats === "function" ? nextStats(prev) : nextStats;
            return (
                prev.quality === next.quality &&
                prev.resolution === next.resolution &&
                prev.buffered === next.buffered &&
                prev.videoId === next.videoId &&
                prev.videoHelper === next.videoHelper &&
                prev.helperStatus === next.helperStatus
            )
                ? prev
                : next;
        });
    }, []);

    const [isPlaying, setIsPlaying] = useState(() => {
        try {
            return Spicetify.Player?.isPlaying?.() ?? false;
        } catch (e) {
            return false;
        }
    });
    const [trackOffsetMs, setTrackOffsetMs] = useState(0);
    // 헬퍼 모드 관련 상태
    const [useHelper, setUseHelper] = useState(false);
    const [helperVideoUrl, setHelperVideoUrl] = useState(null);
    const containerRef = useRef(null);
    const playerRef = useRef(null); // Use ref to hold player instance for reliable cleanup
    const videoRef = useRef(null); // HTML5 video element for helper mode
    const previousFallbackUrlRef = useRef("");
    const [previousFallbackUrl, setPreviousFallbackUrl] = useState("");
    const fallbackTransitionTimerRef = useRef(null);
    const firstLyricTimeRef = useRef(firstLyricTime);
    const trackOffsetMsRef = useRef(trackOffsetMs);
    const abortDownloadRef = useRef(null); // abort function for helper download
    const playerInitRetryRef = useRef(null);
    const lastCaptionDisableRef = useRef(0);
    const youtubeHoldStateRef = useRef({
        isHolding: false,
        primePending: false,
    });
    const brightnessValue = Math.min(Math.max(Number(brightness) || 0, 0), 100);
    const brightnessRatio = brightnessValue / 100;
    const blurValue = Math.min(Math.max(Number(blurAmount) || 0, 0), 80);
    const useCoverMode = coverMode === true;
    const videoScaleValue = Math.min(Math.max(Number(videoScale) || 105, 50), 200);
    const videoScaleRatio = videoScaleValue / 100;
    const videoScaleTransform = videoScaleRatio !== 1 ? ` scale(${videoScaleRatio})` : "";
    const blurCompositeStyle = blurValue ? {
        // The filter value is static for a render. Hint only properties that
        // actually animate so Chromium does not reserve another filter-change layer.
        willChange: "transform, opacity",
        backfaceVisibility: "hidden",
        WebkitBackfaceVisibility: "hidden",
        contain: "paint",
    } : {};
    const videoTransform = useCoverMode
        ? `translate3d(-50%, -50%, 0)${videoScaleTransform}`
        : (blurValue || videoScaleTransform ? `translateZ(0)${videoScaleTransform}` : undefined);

    const albumArtUrl = selectAlbumArtForBackground(
        Spicetify.Player.data?.item?.metadata || {},
        blurValue
    );

    // Capture the previous artwork before the new track is revealed.  The
    // old layer is removed after a single compositor-only crossfade.
    useIsoLayoutEffect(() => {
        const previousUrl = previousFallbackUrlRef.current;
        if (previousUrl && previousUrl !== albumArtUrl) {
            setPreviousFallbackUrl(previousUrl);
            if (fallbackTransitionTimerRef.current) {
                clearTimeout(fallbackTransitionTimerRef.current);
            }
            fallbackTransitionTimerRef.current = setTimeout(() => {
                fallbackTransitionTimerRef.current = null;
                setPreviousFallbackUrl("");
            }, FALLBACK_CROSSFADE_MS + 40);
        }
        previousFallbackUrlRef.current = albumArtUrl;
    }, [trackUri, albumArtUrl]);

    useEffect(() => () => {
        if (fallbackTransitionTimerRef.current) {
            clearTimeout(fallbackTransitionTimerRef.current);
            fallbackTransitionTimerRef.current = null;
        }
    }, []);

    useEffect(() => {
        firstLyricTimeRef.current = firstLyricTime;
    }, [firstLyricTime]);

    useEffect(() => {
        trackOffsetMsRef.current = trackOffsetMs;
    }, [trackOffsetMs]);

    // 헬퍼 모드 설정 확인
    useEffect(() => {
        const helperEnabled = CONFIG?.visual?.["video-helper-enabled"] === true || CONFIG?.visual?.["video-helper-enabled"] === "true";
        setUseHelper(helperEnabled);

        // 설정 변경 이벤트 리스너
        const handleHelperChange = (e) => {
            setUseHelper(e.detail?.enabled === true);
            // 모드 전환 시 상태 초기화
            setHelperVideoUrl(null);
            setIsPlayerReady(false);
        };
        window.addEventListener("ivLyrics:videoHelperChanged", handleHelperChange);
        return () => window.removeEventListener("ivLyrics:videoHelperChanged", handleHelperChange);
    }, []);

    useEffect(() => {
        const reloadCurrentTrack = (event) => {
            const eventTrackUri =
                event?.data?.item?.uri ||
                Spicetify.Player?.data?.item?.uri;
            if (eventTrackUri === trackUri) {
                setVideoLoadRevision((revision) => revision + 1);
            }
        };
        const handleRandomSettingChange = () => {
            setVideoLoadRevision((revision) => revision + 1);
        };
        const handleHiddenCurrentVideo = (event) => {
            const hiddenTrackUri = event?.detail?.trackUri;
            const hiddenVideoId = event?.detail?.videoId;
            const activeVideoInfo = window.ivLyricsActiveCommunityVideoInfo;
            if (
                hiddenTrackUri === trackUri &&
                hiddenVideoId &&
                activeVideoInfo?.trackUri === trackUri &&
                activeVideoInfo?.youtubeVideoId === hiddenVideoId
            ) {
                setVideoLoadRevision((revision) => revision + 1);
            }
        };

        Spicetify.Player?.addEventListener?.("songchange", reloadCurrentTrack);
        window.addEventListener(
            "ivLyrics:communityVideoRandomChanged",
            handleRandomSettingChange
        );
        window.addEventListener(
            "ivLyrics:communityVideoCurrentHidden",
            handleHiddenCurrentVideo
        );
        return () => {
            Spicetify.Player?.removeEventListener?.("songchange", reloadCurrentTrack);
            window.removeEventListener(
                "ivLyrics:communityVideoRandomChanged",
                handleRandomSettingChange
            );
            window.removeEventListener(
                "ivLyrics:communityVideoCurrentHidden",
                handleHiddenCurrentVideo
            );
        };
    }, [trackUri]);

    useEffect(() => {
        window.ivLyricsActiveCommunityVideoInfo = videoInfo?.youtubeVideoId
            ? { trackUri, ...videoInfo }
            : null;

        return () => {
            if (window.ivLyricsActiveCommunityVideoInfo?.trackUri === trackUri) {
                window.ivLyricsActiveCommunityVideoInfo = null;
            }
        };
    }, [trackUri, videoInfo]);

    const reportVideoBackgroundStatus = useCallback((phase, details = {}) => {
        if (typeof onLoadingChange !== "function") return;
        onLoadingChange({
            phase,
            trackUri,
            ...details,
        });
    }, [onLoadingChange, trackUri]);

    const showVideoBackgroundError = useCallback((message) => {
        Toast.error(message);
        reportVideoBackgroundStatus("error");
    }, [reportVideoBackgroundStatus]);

    // Clear the pill when this background instance is removed or its track changes.
    useEffect(() => {
        return () => reportVideoBackgroundStatus("idle");
    }, [reportVideoBackgroundStatus]);

    // 외부에서 전달된 videoInfo가 있으면 사용
    useEffect(() => {
        if (externalVideoInfo && externalVideoInfo.youtubeVideoId) {
            setVideoInfo(externalVideoInfo);
            setIsPlayerReady(false);
            reportVideoBackgroundStatus("loading", {
                label: I18n.t("settings.videoBackground.label") || I18n.t("videoBackground.loading"),
                description: I18n.t("videoBackground.loadingMessage"),
            });
        }
    }, [externalVideoInfo, reportVideoBackgroundStatus]);

    // Load YouTube IFrame API (헬퍼 모드가 아닐 때만)
    useEffect(() => {
        if (useHelper) return;
        if (!window.YT && !document.getElementById("ivlyrics-youtube-iframe-api")) {
            const tag = document.createElement("script");
            tag.id = "ivlyrics-youtube-iframe-api";
            tag.src = "https://www.youtube.com/iframe_api";
            const firstScriptTag = document.getElementsByTagName("script")[0];
            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        }
    }, [useHelper]);

    // Monitor Spotify Playback State
    useEffect(() => {
        const updateState = (event) => {
            if (useHelper) {
                setIsPlaying(isSpotifyPlaybackActive(event?.data));
                return;
            }

            try {
                setIsPlaying(Spicetify.Player?.isPlaying?.() ?? false);
            } catch (e) {
                setIsPlaying(false);
            }
        };

        updateState();
        Spicetify.Player?.addEventListener?.("onplaypause", updateState);
        if (useHelper) {
            Spicetify.Player?.addEventListener?.("songchange", updateState);
        }
        return () => {
            Spicetify.Player?.removeEventListener?.("onplaypause", updateState);
            if (useHelper) {
                Spicetify.Player?.removeEventListener?.("songchange", updateState);
            }
        };
    }, [useHelper]);

    // Fetch Video Info & Manage Player Lifecycle
    useEffect(() => {
        const useRandomCommunityVideo =
            CONFIG?.visual?.["community-video-random"] === true;

        if (!trackUri) {
            setVideoInfo(null);
            setIsPlayerReady(false);
            reportVideoBackgroundStatus("idle");
            return undefined;
        }

        if (externalVideoInfo?.suppressVideoBackground === true) {
            if (playerRef.current) {
                try {
                    playerRef.current.destroy();
                } catch (e) { }
                playerRef.current = null;
            }
            setVideoInfo(null);
            setIsPlayerReady(false);
            reportVideoBackgroundStatus("idle");
            return undefined;
        }

        // 수동 선택은 일반 모드에서 우선하고, 무작위 모드에서는 새 후보를 계산
        if (
            !useRandomCommunityVideo &&
            externalVideoInfo &&
            externalVideoInfo.youtubeVideoId
        ) {
            setVideoInfo(externalVideoInfo);
            setIsPlayerReady(false);
            return undefined;
        }

        // Cleanup previous player immediately when track changes
        if (playerRef.current) {
            try {
                playerRef.current.destroy();
            } catch (e) { }
            playerRef.current = null;
        }

        const trackId = Utils.extractTrackId(trackUri);
        setVideoInfo(null);
        setIsPlayerReady(false);
        reportVideoBackgroundStatus("loading", {
            label: I18n.t("settings.videoBackground.label") || I18n.t("videoBackground.loading"),
            description: I18n.t("videoBackground.loadingMessage"),
        });

        let isMounted = true;

        // 비동기 로드 함수
        const loadVideoInfo = async () => {
            try {
                // 무작위 모드에서는 저장/캐시된 최고 추천보다 커뮤니티 후보를 먼저 선택
                if (trackId && useRandomCommunityVideo) {
                    try {
                        const randomVideo = await Utils.getRandomCommunityVideo(trackUri);
                        if (randomVideo?.youtubeVideoId && isMounted) {
                            videoBackgroundDebug(
                                `[VideoBackground] Using random community video: ${randomVideo.youtubeVideoId}`
                            );
                            setVideoInfo(randomVideo);
                            return;
                        }
                        if (isMounted) {
                            setVideoInfo(null);
                            reportVideoBackgroundStatus("idle");
                            return;
                        }
                    } catch (error) {
                        console.warn(
                            "[VideoBackground] Failed to select a random community video:",
                            error
                        );
                        if (isMounted) {
                            setVideoInfo(null);
                            reportVideoBackgroundStatus("idle");
                            return;
                        }
                    }
                }

                // 1. IndexedDB에서 사용자가 선택한 영상이 있는지 먼저 확인
                try {
                    const savedVideo = await Utils.getSelectedVideo(trackUri);
                    if (savedVideo?.youtubeVideoId && isMounted) {
                        videoBackgroundDebug(`[VideoBackground] Using saved selected video: ${savedVideo.youtubeVideoId}`);
                        setVideoInfo({
                            youtubeVideoId: savedVideo.youtubeVideoId,
                            youtubeTitle: savedVideo.youtubeTitle,
                            captionStartTime: savedVideo.captionStartTime,
                            skipSegments: Utils.normalizeVideoSkipSegments(savedVideo.skipSegments),
                            communityEntryId: savedVideo.communityEntryId,
                            isAutoGenerated: savedVideo.isAutoGenerated
                        });
                        return;
                    }
                } catch (error) {
                    console.error('[VideoBackground] Failed to load saved video:', error);
                }

                if (!trackId) {
                    if (!isMounted) return;
                    setVideoInfo(null);
                    showVideoBackgroundError(I18n.t("videoBackground.localTrackNeedsVideo") || "로컬 곡은 영상 버튼에서 YouTube URL을 직접 지정하세요.");
                    return;
                }

                // 2. 프리페치된 비디오 정보가 있는지 확인
                const prefetchedInfo = typeof Prefetcher !== 'undefined' ? Prefetcher.getVideoInfo(trackUri) : null;

                if (prefetchedInfo?.youtubeVideoId && isMounted) {
                    // 프리페치된 데이터 사용
                    videoBackgroundDebug(`[VideoBackground] Using prefetched video info for trackId: ${trackId}`);
                    setVideoInfo(prefetchedInfo);
                    return;
                }

                const spotifyData = window.SpotifyDataHelper?.extractSpotifyData?.(trackUri);
                const trackMetadata = {
                    trackId,
                    trackName: spotifyData?.name || "",
                    title: spotifyData?.name || "",
                    artists: spotifyData?.artists || [],
                    album: spotifyData?.album || spotifyData?.albumName || "",
                    isrc: spotifyData?.isrc || spotifyData?.external_ids?.isrc || ""
                };
                let trackIsrc = await window.SyncDataService?.resolveTrackIsrc?.(trackId, trackMetadata);
                if (!trackIsrc) {
                    trackIsrc = await window.SyncDataService?.getTrackIsrc?.(trackId, trackMetadata);
                }
                if (!trackIsrc) {
                    if (!isMounted) return;
                    setVideoInfo(null);
                    showVideoBackgroundError("이 곡의 ISRC를 확인할 수 없어 영상 배경을 불러올 수 없습니다.");
                    return;
                }

                // 3. 로컬 캐시 확인 (IndexedDB)
                try {
                    const cachedYouTube = await LyricsCache.getYouTube(trackIsrc);
                    if (cachedYouTube?.youtubeVideoId && isMounted) {
                        videoBackgroundDebug(`[VideoBackground] Using cached YouTube info for ISRC: ${trackIsrc}`);
                        // 캐시 히트 로깅
                        if (window.ApiTracker) {
                            window.ApiTracker.logCacheHit('youtube', `youtube:${trackIsrc}`, {
                                videoId: cachedYouTube.youtubeVideoId,
                                hasCaption: cachedYouTube.captionStartTime != null
                            });
                        }
                        setVideoInfo(cachedYouTube);
                        return;
                    }
                } catch (error) {
                    console.warn('[VideoBackground] Cache check failed:', error);
                }

                // 4. 캐시가 없으면 API 호출 (커뮤니티 우선)
                // 백엔드 엔드포인트: /lyrics/youtube (트랙 메타데이터 포함)
                const clientVersion =
                    (typeof Utils !== "undefined" && Utils.currentVersion) ||
                    window.CONFIG?.version ||
                    "unknown";
                const useCommunity = true;
                const youtubeApiUrl = new URL('https://ivlis.kr/ivLyrics/openvideo/youtube');
                youtubeApiUrl.searchParams.set('isrc', trackIsrc);
                youtubeApiUrl.searchParams.set('trackId', trackId);
                youtubeApiUrl.searchParams.set('useCommunity', useCommunity ? "true" : "false");
                youtubeApiUrl.searchParams.set('client', 'ivLyrics');
                youtubeApiUrl.searchParams.set('clientVersion', clientVersion);
                youtubeApiUrl.searchParams.set('requestVersion', '2');

                if (spotifyData?.name) {
                    youtubeApiUrl.searchParams.set('trackName', spotifyData.name);
                    if (spotifyData.artists?.length) {
                        youtubeApiUrl.searchParams.set('trackArtists', spotifyData.artists.join(', '));
                    }
                    if (spotifyData.album || spotifyData.albumName) {
                        youtubeApiUrl.searchParams.set('album', spotifyData.album || spotifyData.albumName);
                    }
                }
                if (window.SyncDataService?.shouldBypassServerCache?.(trackIsrc)) {
                    youtubeApiUrl.searchParams.set('bypassCache', '1');
                }
                const youtubeUrl = youtubeApiUrl.toString();

                // API 요청 로깅
                let logId = null;
                if (window.ApiTracker) {
                    logId = window.ApiTracker.logRequest('youtube', youtubeUrl, { trackId });
                }

                const res = await fetch(youtubeUrl, {
                    cache: "no-store",
                    headers: {
                        "X-ivLyrics-Client": "ivLyrics",
                        "X-ivLyrics-Request-Version": "2",
                        "X-ivLyrics-Client-Version": clientVersion
                    }
                });
                const data = await res.json();

                if (!isMounted) return;
                if (data.success && data.data?.youtubeVideoId) {
                    // 성공 로깅
                    if (window.ApiTracker && logId) {
                        window.ApiTracker.logResponse(logId, {
                            videoId: data.data?.youtubeVideoId,
                            hasCaption: data.data?.captionStartTime != null
                        }, 'success');
                    }
                    // 로컬 캐시에 저장
                    const resolvedCacheIsrc = window.SyncDataService?.normalizeSyncDataIsrc?.(data.data?.isrc) || trackIsrc;
                    if (resolvedCacheIsrc) {
                        LyricsCache.setYouTube(resolvedCacheIsrc, data.data).catch(() => { });
                    }
                    setVideoInfo(data.data);
                } else {
                    // 실패 로깅
                    if (window.ApiTracker && logId) {
                        window.ApiTracker.logResponse(logId, null, 'error', 'Video not found');
                    }
                    setVideoInfo(null);
                    showVideoBackgroundError(I18n.t("videoBackground.notFound"));
                }
            } catch (error) {
                if (!isMounted) return;
                console.error('[VideoBackground] Failed to load video info:', error);
                setVideoInfo(null);
                showVideoBackgroundError(I18n.t("videoBackground.error"));
            }
        };

        loadVideoInfo();

        return () => {
            isMounted = false;
            // Cleanup on unmount or track change
            if (playerRef.current) {
                try {
                    playerRef.current.destroy();
                } catch (e) { }
                playerRef.current = null;
            }
        };
    }, [trackUri, externalVideoInfo, reportVideoBackgroundStatus, showVideoBackgroundError, videoLoadRevision]);

    // Track-specific sync offset handling
    useEffect(() => {
        if (!trackUri || typeof Utils === "undefined" || typeof Utils.getTrackSyncOffset !== "function") {
            setTrackOffsetMs(0);
            return undefined;
        }

        let isMounted = true;

        const loadOffset = async () => {
            try {
                const offset = (await Utils.getTrackSyncOffset(trackUri)) || 0;
                if (isMounted) {
                    setTrackOffsetMs(offset);
                }
            } catch (error) {
                if (isMounted) {
                    setTrackOffsetMs(0);
                }
            }
        };

        loadOffset();

        const handleOffsetChange = (event) => {
            if (event?.detail?.trackUri === trackUri) {
                setTrackOffsetMs(event.detail.offset || 0);
            }
        };

        window.addEventListener('ivLyrics:offset-changed', handleOffsetChange);

        return () => {
            isMounted = false;
            window.removeEventListener('ivLyrics:offset-changed', handleOffsetChange);
        };
    }, [trackUri]);

    // 헬퍼 모드: 비디오 다운로드 요청
    useEffect(() => {
        if (!useHelper || !videoInfo || !videoInfo.youtubeVideoId) return;

        let isActive = true;

        // 기존 다운로드 중단
        if (abortDownloadRef.current) {
            abortDownloadRef.current();
            abortDownloadRef.current = null;
        }

        // 이전 상태 초기화
        setHelperVideoUrl(null);
        setIsPlayerReady(false);

        setHelperStatus("checking");
        reportVideoBackgroundStatus("loading", {
            label: I18n.t("settings.videoBackground.label") || I18n.t("videoBackground.loading"),
            description: I18n.t("videoBackground.checking"),
        });

        const videoId = videoInfo.youtubeVideoId;
        videoBackgroundDebug(`[VideoBackground] Helper mode: requesting video ${videoId}`);

        // 응답이 늦어질 때 알약의 메시지를 준비 중 상태로 갱신합니다.
        let preparingToastTimeout = setTimeout(() => {
            if (!isActive) return;
            reportVideoBackgroundStatus("loading", {
                label: I18n.t("videoBackground.preparing"),
                description: I18n.t("videoBackground.preparing"),
            });
        }, 1500);

        // 먼저 비디오 상태 확인
        const requestVideo = async () => {
            try {
                // 헬퍼 서버 연결 확인
                const isAvailable = await VideoHelperService.isHelperAvailable();
                if (!isActive) return;
                if (!isAvailable) {
                    setHelperStatus("not-connected");

                    clearTimeout(preparingToastTimeout);
                    showVideoBackgroundError(I18n.t("videoBackground.helperNotConnected"));
                    return;
                }

                // Helper 메시지를 번역된 텍스트로 변환하는 함수
                const translateHelperMessage = (message) => {
                    if (!message) return null;

                    // cookies.txt 파일 관련 메시지
                    if (message.includes("Trying with cookies.txt")) {
                        return I18n.t("videoBackground.tryingCookiesFile");
                    }
                    if (message.includes("Checking video with cookies.txt")) {
                        return I18n.t("videoBackground.checkingWithCookiesFile");
                    }

                    // 브라우저 쿠키 관련 메시지
                    const tryingBrowserMatch = message.match(/Trying with (\w+) cookies/);
                    if (tryingBrowserMatch) {
                        return I18n.t("videoBackground.tryingBrowserCookies", { browser: tryingBrowserMatch[1] });
                    }
                    const checkingBrowserMatch = message.match(/Checking video with (\w+) cookies/);
                    if (checkingBrowserMatch) {
                        return I18n.t("videoBackground.checkingWithBrowserCookies", { browser: checkingBrowserMatch[1] });
                    }

                    // 일반 확인 메시지
                    if (message.includes("Checking video availability")) {
                        return I18n.t("videoBackground.checkingAvailability");
                    }

                    // 연령 제한 관련 에러 메시지
                    if (message.includes("Age-restricted") || message.includes("age-restricted")) {
                        if (message.includes("No cookies.txt or supported browsers")) {
                            return I18n.t("videoBackground.ageRestrictedNoCookies");
                        }
                        return I18n.t("videoBackground.ageRestrictedFailed");
                    }

                    // 이미 다운로드된 영상
                    if (message.includes("Video already downloaded") || message.includes("Video already available")) {
                        return I18n.t("videoBackground.videoAlreadyDownloaded");
                    }

                    // 다운로드 중 메시지 (퍼센트 추출)
                    const downloadingMatch = message.match(/Downloading:\s*([\d.]+)%/);
                    if (downloadingMatch) {
                        return I18n.t("videoBackground.downloading", { percent: Math.round(parseFloat(downloadingMatch[1])) });
                    }

                    // 기본값: 원본 메시지 반환
                    return message;
                };

                // 비디오 요청 (SSE 스트림)
                abortDownloadRef.current = VideoHelperService.requestVideo(videoId, {
                    onProgress: (progress) => {
                        if (!isActive) return;
                        if (progress?.status === "downloading") setHelperStatus("downloading");
                        else if (progress?.status === "processing") setHelperStatus("processing");
                        else if (progress?.status === "checking") setHelperStatus("checking");
                        // progress 이벤트가 오면 preparing timeout 취소
                        clearTimeout(preparingToastTimeout);

                        const percent = Math.round(progress.percent || 0);
                        const translatedMsg = translateHelperMessage(progress.message);

                        if (progress.status === "downloading") {
                            const message = I18n.t("videoBackground.downloading", { percent });
                            reportVideoBackgroundStatus("loading", {
                                label: message,
                                description: message,
                            });
                        } else if (progress.status === "processing") {
                            const message = I18n.t("videoBackground.processing");
                            reportVideoBackgroundStatus("loading", {
                                label: message,
                                description: message,
                            });
                        } else if (progress.status === "checking") {
                            // checking 상태일 때 메시지가 있으면 번역된 메시지 사용
                            const checkingMsg = translatedMsg || I18n.t("videoBackground.checking");
                            reportVideoBackgroundStatus("loading", {
                                label: checkingMsg,
                                description: checkingMsg,
                            });
                        }
                    },
                    onComplete: (url) => {
                        if (!isActive) return;
                        setHelperStatus("ready");
                        clearTimeout(preparingToastTimeout);
                        videoBackgroundDebug(`[VideoBackground] Helper: video ready, setting URL: ${url}`);

                        // URL 유효성 확인
                        if (!url || typeof url !== 'string' || !url.startsWith('http')) {
                            console.error(`[VideoBackground] Invalid video URL received: ${url}`);
                            showVideoBackgroundError(I18n.t("videoBackground.helperError"));
                            return;
                        }

                        setHelperVideoUrl(url);
                        const message = I18n.t("videoBackground.processing");
                        reportVideoBackgroundStatus("loading", {
                            label: message,
                            description: message,
                        });
                    },
                    onError: (message) => {
                        if (!isActive) return;
                        setHelperStatus("error");
                        clearTimeout(preparingToastTimeout);
                        console.error(`[VideoBackground] Helper error: ${message}`);

                        // 에러 메시지 번역
                        const translatedError = translateHelperMessage(message) || I18n.t("videoBackground.helperError");
                        showVideoBackgroundError(translatedError);
                    },
                });
            } catch (e) {
                if (!isActive) return;
                clearTimeout(preparingToastTimeout);
                console.error("[VideoBackground] Helper request failed:", e);
                showVideoBackgroundError(I18n.t("videoBackground.helperError"));
            }
        };

        requestVideo();

        return () => {
            isActive = false;
            clearTimeout(preparingToastTimeout);
            if (abortDownloadRef.current) {
                abortDownloadRef.current();
                abortDownloadRef.current = null;
            }
        };
    }, [useHelper, videoInfo, reportVideoBackgroundStatus, showVideoBackgroundError]);

    // 헬퍼 모드: HTML5 video 재생 및 동기화
    useEffect(() => {
        if (!useHelper || !helperVideoUrl || !videoRef.current) return;

        videoBackgroundDebug(`[VideoBackground] Loading helper video from: ${helperVideoUrl}`);
        reportVideoBackgroundStatus("loading", {
            label: I18n.t("settings.videoBackground.label") || I18n.t("videoBackground.loading"),
            description: I18n.t("videoBackground.loadingMessage"),
        });

        const video = videoRef.current;
        let didReportReady = false;
        let readinessTimeout = null;
        video.src = helperVideoUrl;
        video.muted = true;
        video.loop = false;

        const handleCanPlay = () => {
            if (readinessTimeout) {
                clearTimeout(readinessTimeout);
                readinessTimeout = null;
            }
            let readySyncState = null;
            // 영상이 준비되면 즉시 현재 Spotify 위치로 동기화
            if (videoInfo) {
                const spotifyTime = Spicetify.Player.getProgress() / 1000;
                const lyricsStartTime = getLyricsStartTimeSeconds(firstLyricTimeRef.current);
                const globalDelayMs = typeof CONFIG !== "undefined" && CONFIG.visual ? Number(CONFIG.visual.delay || 0) : 0;
                const globalSyncOffsetMs = Number(window.Utils?.getGlobalSyncOffset?.() ?? CONFIG?.visual?.["global-sync-offset"] ?? 0) || 0;
                const additionalDelaySeconds = (trackOffsetMsRef.current + globalDelayMs + globalSyncOffsetMs) / 1000;
                readySyncState = resolveVideoSyncState({
                    spotifyTime,
                    lyricsStartTime,
                    videoInfo,
                    additionalDelaySeconds,
                    mapVideoTime: Utils.mapVideoTimeWithSkipSegments.bind(Utils),
                });
                const targetVideoTime = wrapVideoSyncTime(readySyncState.targetVideoTime, video.duration);

                if (
                    (!Number.isFinite(video.currentTime) || Math.abs(video.currentTime - targetVideoTime) > 0.05)
                ) {
                    video.currentTime = targetVideoTime;
                }

                if (readySyncState.shouldHoldAtStart && !video.paused) {
                    video.pause();
                }
            }

            setIsPlayerReady(true);
            if (!didReportReady) {
                didReportReady = true;
                reportVideoBackgroundStatus("complete");
            }
            if (isSpotifyPlaybackActive() && !readySyncState?.shouldHoldAtStart) {
                video.play().catch(() => { });
            } else if (!video.paused) {
                video.pause();
            }
        };

        const handleError = (e) => {
            if (readinessTimeout) {
                clearTimeout(readinessTimeout);
                readinessTimeout = null;
            }
            console.error("[VideoBackground] Helper video error:", e, "src:", video.src);
            setIsPlayerReady(false);
            showVideoBackgroundError(I18n.t("videoBackground.helperError"));
        };

        const handleLoadStart = () => {
            videoBackgroundDebug("[VideoBackground] Video loadstart");
        };
        const handleLoadedMetadata = () => {
            videoBackgroundDebug("[VideoBackground] Video loadedmetadata, duration:", video.duration);
        };

        video.addEventListener('canplay', handleCanPlay);
        video.addEventListener('error', handleError);
        video.addEventListener('loadstart', handleLoadStart);
        video.addEventListener('loadedmetadata', handleLoadedMetadata);

        readinessTimeout = setTimeout(() => {
            readinessTimeout = null;
            setIsPlayerReady(false);
            showVideoBackgroundError(I18n.t("videoBackground.helperError"));
        }, 15000);

        video.load();

        return () => {
            if (readinessTimeout) {
                clearTimeout(readinessTimeout);
                readinessTimeout = null;
            }
            video.removeEventListener('canplay', handleCanPlay);
            video.removeEventListener('error', handleError);
            video.removeEventListener('loadstart', handleLoadStart);
            video.removeEventListener('loadedmetadata', handleLoadedMetadata);
            video.pause();
            video.removeAttribute('src');
            video.load();
        };
    }, [useHelper, helperVideoUrl, videoInfo, reportVideoBackgroundStatus, showVideoBackgroundError]);


    // 통계 업데이트
    useEffect(() => {
        const refreshStats = () => {
            // 헬퍼 모드
            if (useHelper && videoInfo) {  //
                const video = videoRef.current;

                // 비디오가 준비되지 않았을 때
                if (!isPlayerReady || !video) {
                    updateStats({
                        quality: '-',
                        resolution: '-',
                        buffered: '-',
                        videoId: videoInfo?.youtubeVideoId || '-',
                        videoHelper: 'Helper (Local)',
                        helperStatus: helperStatus  //
                    });
                    return;
                }

                // 비디오가 준비되었을 때
                try {
                    const buffered = video.buffered;
                    const bufferedPercent = buffered.length > 0
                        ? Math.round((buffered.end(buffered.length - 1) / video.duration) * 100)
                        : 0;

                    updateStats({
                        quality: 'local',
                        resolution: `${video.videoWidth}x${video.videoHeight}`,
                        buffered: `${bufferedPercent}%`,
                        videoId: videoInfo?.youtubeVideoId || '-',
                        videoHelper: 'Helper (Local)',
                        helperStatus: helperStatus
                    });
                } catch (e) {}
            }
            // 일반 모드
            else if (!useHelper && playerRef.current && isPlayerReady) {
                const player = playerRef.current;
                if (typeof player.getPlaybackQuality !== 'function') return;

                try {
                    const quality = player.getPlaybackQuality();
                    const videoData = player.getVideoData();
                    const videoLoadedFraction = player.getVideoLoadedFraction();

                    const qualityMap = {
                        'hd2160': '3840x2160', 'hd1440': '2560x1440',
                        'hd1080': '1920x1080', 'hd720': '1280x720',
                        'large': '854x480', 'medium': '640x360',
                        'small': '426x240', 'tiny': '256x144'
                    };

                    updateStats({
                        quality: quality || '-',
                        resolution: qualityMap[quality] || '-',
                        buffered: `${Math.round(videoLoadedFraction * 100)}%`,
                        videoId: videoData?.video_id || '-',
                        videoHelper: 'YouTube (Iframe)',
                        helperStatus: 'off'
                    });
                } catch (e) {}
            }
        };

        if (!showStats) {
            return undefined;
        }

        if (document.visibilityState !== 'visible') {
            return undefined;
        }

        const interval = setInterval(refreshStats, 1000);
        refreshStats(); //
        return () => clearInterval(interval);
    }, [useHelper, isPlayerReady, videoInfo, helperStatus, showStats, updateStats]);

    // 키보드 단축키 (Shift + S)
    useEffect(() => {
        const handleKeyPress = (e) => {
            const activeElement = document.activeElement;
            const tagName = activeElement?.tagName?.toLowerCase();
            if (tagName === 'input' || tagName === 'textarea' || activeElement?.isContentEditable) {
                return;
            }

            if (e.repeat) {
                return;
            }

            if (e.shiftKey && e.code === 'KeyS') {
                setShowStats(prev => !prev);
            }
        };
        window.addEventListener('keydown', handleKeyPress);
        return () => window.removeEventListener('keydown', handleKeyPress);
    }, []);

    useEffect(() => {
        const lyricsStartTime = getLyricsStartTimeSeconds(firstLyricTimeRef.current);
        const globalDelayMs = typeof CONFIG !== "undefined" && CONFIG.visual ? Number(CONFIG.visual.delay || 0) : 0;
        const globalSyncOffsetMs = Number(window.Utils?.getGlobalSyncOffset?.() ?? CONFIG?.visual?.["global-sync-offset"] ?? 0) || 0;
        const syncState = videoInfo
            ? resolveVideoSyncState({
                spotifyTime: Spicetify.Player.getProgress() / 1000,
                lyricsStartTime,
                videoInfo,
                additionalDelaySeconds: (trackOffsetMsRef.current + globalDelayMs + globalSyncOffsetMs) / 1000,
                mapVideoTime: Utils.mapVideoTimeWithSkipSegments.bind(Utils),
            })
            : null;
        const shouldPlayVideo = isPlaying && !syncState?.shouldHoldAtStart;

        if (useHelper) {
            const video = videoRef.current;
            if (!video || !isPlayerReady) return;

            if (!shouldPlayVideo) {
                if (!video.paused) {
                    video.pause();
                }
                return;
            }

            if (video.paused) {
                video.play().catch(() => { });
            }
            return;
        }

        const player = playerRef.current;
        if (!player || !isPlayerReady || !syncState || typeof player.getPlayerState !== 'function') return;

        try {
            // Playback events must use the same hold/seek state as the timer so
            // pausing Spotify cannot interrupt an in-flight start-frame refresh.
            syncYouTubePlayerTimeline({
                player,
                targetVideoTime: wrapVideoSyncTime(syncState.targetVideoTime, player.getDuration?.()),
                shouldHoldAtStart: syncState.shouldHoldAtStart,
                shouldPlay: isPlaying,
                holdState: youtubeHoldStateRef.current,
            });
        } catch (e) { }
    }, [useHelper, isPlaying, isPlayerReady, helperVideoUrl, videoInfo]);

    // 헬퍼 모드: 동기화 로직
    useEffect(() => {
        if (!useHelper || !videoRef.current || !isPlayerReady || !videoInfo || document.visibilityState !== 'visible') return;

        const video = videoRef.current;

        const syncVideo = () => {
            const spotifyTime = Spicetify.Player.getProgress() / 1000;
            const lyricsStartTime = getLyricsStartTimeSeconds(firstLyricTime);
            const globalDelayMs = typeof CONFIG !== "undefined" && CONFIG.visual ? Number(CONFIG.visual.delay || 0) : 0;
            const globalSyncOffsetMs = Number(window.Utils?.getGlobalSyncOffset?.() ?? CONFIG?.visual?.["global-sync-offset"] ?? 0) || 0;
            const additionalDelaySeconds = (trackOffsetMs + globalDelayMs + globalSyncOffsetMs) / 1000;
            const syncState = resolveVideoSyncState({
                spotifyTime,
                lyricsStartTime,
                videoInfo,
                additionalDelaySeconds,
                mapVideoTime: Utils.mapVideoTimeWithSkipSegments.bind(Utils),
            });
            const targetVideoTime = wrapVideoSyncTime(syncState.targetVideoTime, video.duration);
            const currentVideoTime = video.currentTime;

            if (
                !Number.isFinite(currentVideoTime) ||
                Math.abs(currentVideoTime - targetVideoTime) > VIDEO_SYNC_SEEK_THRESHOLD_SECONDS
            ) {
                video.currentTime = targetVideoTime;
            }

            if (!isPlaying || syncState.shouldHoldAtStart) {
                if (!video.paused) {
                    video.pause();
                }
            } else if (video.paused) {
                video.play().catch(() => { });
            }
        };

        syncVideo();
        const syncInterval = setInterval(syncVideo, VIDEO_SYNC_INTERVAL_MS);

        return () => clearInterval(syncInterval);
    }, [useHelper, isPlayerReady, videoInfo, firstLyricTime, trackOffsetMs, isPlaying]);

    // 일반 모드 (YouTube IFrame): Initialize Player when videoInfo is available
    useEffect(() => {
        if (useHelper) return; // 헬퍼 모드면 스킵
        if (!videoInfo || !videoInfo.youtubeVideoId || !containerRef.current) return;

        reportVideoBackgroundStatus("loading", {
            label: I18n.t("settings.videoBackground.label") || I18n.t("videoBackground.loading"),
            description: I18n.t("videoBackground.loadingMessage"),
        });

        let isCancelled = false;
        let didReportReady = false;
        let playerLifecycleFailed = false;
        let playerReadyDeadline = null;
        const captionDisableTimers = [];
        const scheduleCaptionDisable = (player) => {
            disableYouTubeCaptions(player);
            [250, 1000, 2500].forEach((delay) => {
                const timer = setTimeout(() => {
                    if (!isCancelled) disableYouTubeCaptions(player);
                }, delay);
                captionDisableTimers.push(timer);
            });
        };
        const failPlayerLifecycle = (error) => {
            if (isCancelled || didReportReady || playerLifecycleFailed) return;
            playerLifecycleFailed = true;
            if (playerInitRetryRef.current) {
                clearTimeout(playerInitRetryRef.current);
                playerInitRetryRef.current = null;
            }
            if (playerReadyDeadline) {
                clearTimeout(playerReadyDeadline);
                playerReadyDeadline = null;
            }
            if (error) {
                console.error("[VideoBackground] YouTube player failed:", error);
            }
            setIsPlayerReady(false);
            youtubeHoldStateRef.current.isHolding = false;
            youtubeHoldStateRef.current.primePending = false;
            showVideoBackgroundError(I18n.t("videoBackground.error"));
        };
        const markPlayerReady = (player) => {
            if (isCancelled || playerLifecycleFailed || !player) return false;
            playerRef.current = player;
            if (!didReportReady) {
                didReportReady = true;
                if (playerReadyDeadline) {
                    clearTimeout(playerReadyDeadline);
                    playerReadyDeadline = null;
                }
                setIsPlayerReady(true);
                reportVideoBackgroundStatus("complete");
                scheduleCaptionDisable(player);
            }
            return true;
        };

        playerReadyDeadline = setTimeout(() => {
            failPlayerLifecycle(new Error("YouTube player readiness timed out."));
        }, 15000);

        // Double check cleanup
        if (playerRef.current) {
            try {
                playerRef.current.destroy();
            } catch (e) { }
            playerRef.current = null;
        }

        const initPlayer = () => {
            if (isCancelled || playerLifecycleFailed) return;
            if (!window.YT || !window.YT.Player) {
                playerInitRetryRef.current = setTimeout(initPlayer, 100);
                return;
            }

            playerInitRetryRef.current = null;
            if (isCancelled || !containerRef.current) {
                return;
            }

            // Ensure container is empty before creating new player
            // containerRef.current.innerHTML = ""; // YT.Player replaces the element, so we need a wrapper or let it replace a child. 
            // Actually YT.Player replaces the target element. If we use a ref to a div, that div gets replaced by the iframe.
            // If we destroy the player, does it restore the div? No.
            // So we need to ensure we have a fresh target element.
            // The easiest way is to let React handle the DOM node. 
            // If we destroy the player, the iframe is removed. We might need to recreate the container div?
            // Actually, YT.Player(id|element) replaces the element. 
            // If we use a ref, we should probably use a wrapper and append a child to it, or handle the ref carefully.

            // Better approach: Create a temporary div inside the container
            const playerDiv = document.createElement('div');
            containerRef.current.innerHTML = ''; // Clear container
            containerRef.current.appendChild(playerDiv);

            try {
                const newPlayer = new window.YT.Player(playerDiv, {
                    height: "100%",
                    width: "100%",
                    videoId: videoInfo.youtubeVideoId,
                    playerVars: {
                        autoplay: 1,
                        controls: 0,
                        disablekb: 1,
                        fs: 0,
                        rel: 0,
                        iv_load_policy: 3,
                        cc_load_policy: 0,
                        mute: 1,
                        origin: window.location.origin,
                    },
                    events: {
                        onReady: (event) => {
                            if (!markPlayerReady(event?.target)) {
                                if (isCancelled || playerLifecycleFailed) {
                                    try {
                                        event?.target?.destroy?.();
                                    } catch (e) { }
                                }
                                return;
                            }
                            event.target.mute();
                            event.target.playVideo();
                        },
                        onError: (event) => {
                            failPlayerLifecycle(new Error(`YouTube player error: ${event?.data ?? "unknown"}`));
                        },
                        onStateChange: (event) => {
                            if (isCancelled || playerLifecycleFailed) return;
                            const state = event?.data;
                            settleYouTubeHoldPrime({
                                player: event?.target,
                                playerState: state,
                                holdState: youtubeHoldStateRef.current,
                            });
                            if ([1, 2, 3, 5].includes(state) && !didReportReady) {
                                markPlayerReady(event?.target);
                            }
                            if (state === window.YT?.PlayerState?.PLAYING || state === window.YT?.PlayerState?.CUED) {
                                disableYouTubeCaptions(event.target);
                            }
                        },
                    },
                });
                // YT.Player returns the instance before onReady.
                playerRef.current = newPlayer;
            } catch (error) {
                failPlayerLifecycle(error);
            }
        };

        initPlayer();

        return () => {
            isCancelled = true;

            if (playerInitRetryRef.current) {
                clearTimeout(playerInitRetryRef.current);
                playerInitRetryRef.current = null;
            }
            if (playerReadyDeadline) {
                clearTimeout(playerReadyDeadline);
                playerReadyDeadline = null;
            }
            captionDisableTimers.forEach((timer) => clearTimeout(timer));

            if (playerRef.current) {
                try {
                    playerRef.current.destroy();
                } catch (e) { }
                playerRef.current = null;
            }
            youtubeHoldStateRef.current.isHolding = false;
            youtubeHoldStateRef.current.primePending = false;
        };

    }, [useHelper, videoInfo, reportVideoBackgroundStatus, showVideoBackgroundError]);

    // 일반 모드 (YouTube IFrame): Sync Logic
    useEffect(() => {
        if (useHelper || document.visibilityState !== 'visible') return; // 헬퍼 모드면 스킵

        const syncVideo = () => {
            const player = playerRef.current;
            if (!player || !isPlayerReady || !videoInfo) return;
            // Check if player has methods (sometimes it's not fully ready even if object exists)
            if (typeof player.getPlayerState !== 'function') return;

            try {
                const st = player.getPlayerState();
                if (st === 1 || st === 3) {
                    const now = Date.now();
                    if (now - lastCaptionDisableRef.current > 5000) {
                        lastCaptionDisableRef.current = now;
                        disableYouTubeCaptions(player);
                    }
                }
            } catch (e) {}

            const spotifyTime = Spicetify.Player.getProgress() / 1000;
            const lyricsStartTime = getLyricsStartTimeSeconds(firstLyricTime);
            const globalDelayMs = typeof CONFIG !== "undefined" && CONFIG.visual ? Number(CONFIG.visual.delay || 0) : 0;
            const globalSyncOffsetMs = Number(window.Utils?.getGlobalSyncOffset?.() ?? CONFIG?.visual?.["global-sync-offset"] ?? 0) || 0;
            const additionalDelaySeconds = (trackOffsetMs + globalDelayMs + globalSyncOffsetMs) / 1000;
            const syncState = resolveVideoSyncState({
                spotifyTime,
                lyricsStartTime,
                videoInfo,
                additionalDelaySeconds,
                mapVideoTime: Utils.mapVideoTimeWithSkipSegments.bind(Utils),
            });
            const videoDuration = typeof player.getDuration === 'function'
                ? player.getDuration()
                : 0;
            const targetVideoTime = wrapVideoSyncTime(syncState.targetVideoTime, videoDuration);
            syncYouTubePlayerTimeline({
                player,
                targetVideoTime,
                shouldHoldAtStart: syncState.shouldHoldAtStart,
                shouldPlay: isPlaying,
                holdState: youtubeHoldStateRef.current,
            });
        };

        syncVideo();
        const syncInterval = setInterval(syncVideo, VIDEO_SYNC_INTERVAL_MS);

        return () => clearInterval(syncInterval);
    }, [useHelper, isPlayerReady, videoInfo, firstLyricTime, trackOffsetMs, isPlaying]);

    // Render Album Art Background (Fallback).  Keep an outgoing image layer
    // around for one short crossfade so a track change never exposes an empty
    // or black frame while the new video is loading.
    const fallbackStyle = {
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        backgroundSize: "cover",
        backgroundPosition: "center",
        filter: `brightness(${brightnessRatio}) blur(${blurValue}px)`,
        transform: "translateZ(0) scale(1.1)",
        ...blurCompositeStyle,
        pointerEvents: "none",
    };
    const renderFallback = () => react.createElement(
        react.Fragment,
        null,
        previousFallbackUrl && previousFallbackUrl !== albumArtUrl && react.createElement("div", {
            className: "ivlyrics-video-background-fallback ivlyrics-video-background-fallback-outgoing",
            style: {
                ...fallbackStyle,
                backgroundImage: `url(${previousFallbackUrl})`,
                zIndex: 0,
            },
        }),
        react.createElement("div", {
            className: `ivlyrics-video-background-fallback${previousFallbackUrl && previousFallbackUrl !== albumArtUrl ? " ivlyrics-video-background-fallback-incoming" : ""}`,
            style: {
                ...fallbackStyle,
                backgroundImage: albumArtUrl ? `url(${albumArtUrl})` : "none",
                backgroundColor: "var(--spice-main, #121212)",
                zIndex: 0,
            },
        })
    );

    // 헬퍼 모드용 video 태그 스타일
    const helperVideoStyle = {
        position: "absolute",
        top: useCoverMode ? "50%" : 0,
        left: useCoverMode ? "50%" : 0,
        width: useCoverMode ? "177.78vh" : "100%",
        height: useCoverMode ? "56.25vw" : "100%",
        minWidth: useCoverMode ? "100%" : undefined,
        minHeight: useCoverMode ? "100%" : undefined,
        transform: videoTransform,
        opacity: isPlayerReady && isPlaying ? 1 : 0,
        transition: "opacity 0.32s cubic-bezier(0.22, 1, 0.36, 1)",
        zIndex: 1,
        pointerEvents: "none",
        filter: blurValue ? `blur(${blurValue}px)` : "none",
        objectFit: useCoverMode ? "cover" : "contain",
        ...blurCompositeStyle,
    };

    return react.createElement("div", {
        style: {
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            overflow: "hidden",
            zIndex: 0,
            isolation: "isolate",
        }
    },
        renderFallback(),


        showStats && react.createElement("div", {
            style: {
                position: "absolute",
                top: "20px",
                right: "20px",
                zIndex: 100,
                background: "rgba(0, 0, 0, 0.85)",
                backdropFilter: "blur(10px)",
                padding: "16px",
                borderRadius: "8px",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                fontFamily: "monospace",
                fontSize: "12px",
                color: "#fff",
                minWidth: "200px",
                boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
            }
        },
            react.createElement("div", {
                style: { marginBottom: "8px", fontWeight: "bold", fontSize: "13px" }
            }, "  Video Stats"),
            react.createElement("div", {
                style: { display: "flex", justifyContent: "space-between", marginBottom: "4px" }
            },
                react.createElement("span", {}, "Quality:"),
                react.createElement("span", { style: { color: "#1DB954" } }, stats.quality)
            ),
            react.createElement("div", {
                style: { display: "flex", justifyContent: "space-between", marginBottom: "4px" }
            },
                react.createElement("span", {}, "Resolution:"),
                react.createElement("span", { style: { color: "#1DB954" } }, stats.resolution)
            ),
            react.createElement("div", {
                style: { display: "flex", justifyContent: "space-between", marginBottom: "4px" }
            },
                react.createElement("span", {}, "Buffered:"),
                react.createElement("span", { style: { color: "#1DB954" } }, stats.buffered)
            ),
            react.createElement("div", {
                style: { display: "flex", justifyContent: "space-between", marginBottom: "4px" }
            },
            react.createElement("span", {}, "Source:"),
            react.createElement("span", {
                style: {
                    color: stats.videoHelper?.includes("Helper") ? "#ff9800" : "#1DB954",
                    fontWeight: "bold"
                }
            }, stats.videoHelper)
            ),

            react.createElement("div", {
                style: { display: "flex", justifyContent: "space-between", marginBottom: "4px" }
            },
                react.createElement("span", {}, "Helper Status:"),
                react.createElement("span", {
                style: {
                    color:
                        stats.helperStatus === "ready" ? "#1DB954" :
                        stats.helperStatus === "downloading" ? "#ff9800" :
                        stats.helperStatus === "not-connected" ? "#ff5252" :
                        "#888",
                    fontWeight: "bold"
                    }
            }, stats.helperStatus)
            ),


            react.createElement("div", {
                style: {
                    display: "flex",
                    justifyContent: "space-between",
                    marginTop: "8px",
                    paddingTop: "8px",
                    borderTop: "1px solid rgba(255, 255, 255, 0.1)"
                }
            },
                react.createElement("span", {}, "Video ID:"),
                react.createElement("span", {
                    style: {
                        color: "#888",
                        fontSize: "10px",
                        maxWidth: "100px",
                        overflow: "hidden",
                        textOverflow: "ellipsis"
                    }
                }, stats.videoId)
            ),
            react.createElement("div", {
                style: {
                    marginTop: "8px",
                    paddingTop: "8px",
                    borderTop: "1px solid rgba(255, 255, 255, 0.1)",
                    fontSize: "10px",
                    color: "#888",
                    textAlign: "center"
                }
            }, "Press Shift+S to toggle")
        ),

        // 헬퍼 모드: HTML5 video 태그
        useHelper && react.createElement("video", {
            ref: videoRef,
            className: "ivlyrics-video-background-media",
            style: helperVideoStyle,
            muted: true,
            playsInline: true,
            loop: false,
        }),
        // 일반 모드: YouTube IFrame 컨테이너
        !useHelper && react.createElement("div", {
            ref: containerRef,
            className: "ivlyrics-video-background-media",
            style: {
                position: "absolute",
                top: useCoverMode ? "50%" : 0,
                left: useCoverMode ? "50%" : 0,
                width: useCoverMode ? "177.78vh" : "100%", // 16:9 aspect ratio: 100vh * 16/9
                height: useCoverMode ? "56.25vw" : "100%", // 16:9 aspect ratio: 100vw * 9/16
                minWidth: useCoverMode ? "100%" : undefined,
                minHeight: useCoverMode ? "100%" : undefined,
                transform: videoTransform,
                opacity: isPlayerReady && isPlaying ? 1 : 0, // Hide when paused or not ready
                transition: "opacity 0.32s cubic-bezier(0.22, 1, 0.36, 1)",
                zIndex: 1,
                pointerEvents: "none",
                filter: blurValue ? `blur(${blurValue}px)` : "none",
                ...blurCompositeStyle,
            }
        }),
        react.createElement("div", {
            style: {
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                backgroundColor: "black",
                opacity: 1 - brightnessRatio,
                zIndex: 2,
                pointerEvents: "none"
            }
        })
    );
};

window.VideoBackground = VideoBackground;
